### ISSUE TITLE
Add La WUFA roster

### ISSUE THREAD

**Issue by ritotn** [WilliamsUltimate/wufo-website#33]
Along with changes to their page as they see fit

**Comment by ritotn** [comment]
What's left:
- [x] Add photos to roster

- [x] Add caption to landing page

**Comment by alansun25** [comment]
@etchenko any word on when we're gonna get this stuff?

**Comment by ritotn** [comment]
#43

**Comment by etchenko** [comment]
They liked the caption we currently has so nothing needs to be changed there
