### ISSUE TITLE
Add a new 2021-22 roster and archive the old one

### ISSUE THREAD

**Issue by kaizencc** [WilliamsUltimate/wufo-website#48]
Where are all the frosh on the 20-21 roster? Someone should go collect their photos and update it. 

We should have a new roster up for the 21-22 year as well. I'd like to see the old roster archived on a `2020-2021` tab (inside the `Roster` tab) so that we aren't just erased and the new roster be the default one.

**Comment by kaizencc** [comment]
@alansun25 @ritot don't make it open source if you don't want me to cut tickets with you :). Where's the updated roster? You guys must be starting recruitment at this point right?

**Comment by ritotn** [comment]
We're sunsetting this repo and migrating to [`/williamsultimate`](https://github.com/WilliamsUltimate/williamsultimate). Please add your suggestions there! Thanks 😊
